format = 1
distribution = "Arach OS"

[[component]]
name = "arach-kernel"
repository = "https://github.com/SisyphusAeolides/Arach-Kernel.git"
revision = "eb212d3a64298fce3a81b0d0dae6c72f1cc22183"
role = "kernel"

[[component]]
name = "slope"
repository = "https://github.com/SisyphusAeolides/Slope.git"
revision = "b3decb53e71bb3c5d5fc55047451bcf9cef7eff9"
role = "userspace-abi"

[[component]]
name = "push"
repository = "https://github.com/SisyphusAeolides/Push.git"
revision = "5bd361b86c048b60b6a8422a8e173ea0ec867bff"
role = "pid1"

[[component]]
name = "granite"
repository = "https://github.com/SisyphusAeolides/Granite.git"
revision = "c4c36daa40ed79a81751b00dcc4cb6eb4f4d9ac5"
role = "bootloader"

[[component]]
name = "corinth"
repository = "https://github.com/SisyphusAeolides/Corinth.git"
revision = "036a9caecf30926d116a361ce7d4f7a6fc455989"
role = "package-manager"

[[component]]
name = "arach-packages"
repository = "https://github.com/SisyphusAeolides/Arach-Packages.git"
revision = "e0da14a4c48f2cf714dbb200a2229aa9e3281d51"
role = "package-recipes"

[[component]]
name = "arach-hwd"
repository = "https://github.com/SisyphusAeolides/Arach-HWD.git"
revision = "569c40a530fb8e5fe9fc618b97c7ae4a5795f634"
role = "hardware-provisioning"

[[component]]
name = "libinput-rs"
repository = "https://github.com/SisyphusAeolides/libinput-rs.git"
revision = "8c25705118e540a01e478c39abb36a398401371f"
role = "input-stack"

[[component]]
name = "elan-guardian"
repository = "https://github.com/SisyphusAeolides/elan-guardian.git"
revision = "1b3403da938ebd8be9b81de4df00680e0c3fc7ed"
role = "input-recovery"

[[component]]
name = "tuned-rs"
repository = "https://github.com/SisyphusAeolides/tuned-rs.git"
revision = "28fbe938aa9afb647c1a4fa066417c6db1b2abfe"
role = "system-tuning"

[[component]]
name = "ccze-rs"
repository = "https://github.com/SisyphusAeolides/ccze-rs.git"
revision = "e42cced69ca8a93087c197261e5a9e322c093422"
role = "log-presentation"
