format = 1
distribution = "Arach OS"

[[component]]
name = "arach-kernel"
repository = "https://github.com/SisyphusAeolides/Arach-Kernel.git"
revision = "cf4b56a1d7e801b219b424d75bfe31c1ec73c42e"
role = "kernel"

[[component]]
name = "slope"
repository = "https://github.com/SisyphusAeolides/Slope.git"
revision = "b3decb53e71bb3c5d5fc55047451bcf9cef7eff9"
role = "userspace-abi"

[[component]]
name = "push"
repository = "https://github.com/SisyphusAeolides/Push.git"
revision = "b4e563547936595def7bc5097fb0bfbe7a1750e7"
role = "pid1"

[[component]]
name = "granite"
repository = "https://github.com/SisyphusAeolides/Granite.git"
revision = "cb6fc0f5d0b5494d2ae8997b71c410cd33016be7"
role = "bootloader"

[[component]]
name = "corinth"
repository = "https://github.com/SisyphusAeolides/Corinth.git"
revision = "45e826f575f084e47f1b15f3ff19f3cc5e10ede8"
role = "package-manager"

[[component]]
name = "arach-packages"
repository = "https://github.com/SisyphusAeolides/Arach-Packages.git"
revision = "306a2d38086fe9de533a4240c3e3e4f74eb5af4a"
role = "package-recipes"

[[component]]
name = "arach-hwd"
repository = "https://github.com/SisyphusAeolides/Arach-HWD.git"
revision = "9cfee7dd0dc2151bea5810fabf9cb65ec7bf8a56"
role = "hardware-provisioning"

[[component]]
name = "libinput-rs"
repository = "https://github.com/SisyphusAeolides/libinput-rs.git"
revision = "8c25705118e540a01e478c39abb36a398401371f"
role = "input-stack"

[[component]]
name = "elan-guardian"
repository = "https://github.com/SisyphusAeolides/elan-guardian.git"
revision = "1b3403da938ebd8be9b81de4df00680e0c3fc7ed"
role = "input-recovery"

[[component]]
name = "tuned-rs"
repository = "https://github.com/SisyphusAeolides/tuned-rs.git"
revision = "28fbe938aa9afb647c1a4fa066417c6db1b2abfe"
role = "system-tuning"

[[component]]
name = "ccze-rs"
repository = "https://github.com/SisyphusAeolides/ccze-rs.git"
revision = "e42cced69ca8a93087c197261e5a9e322c093422"
role = "log-presentation"
