format = 1
distribution = "Arach OS"
root_layout = "posix"
boot_bundle_source = "/run/arach-live/boot-bundle"
repository_generation = "/run/arach-live/repository/system.gen"
manifest = "/run/arach-live/image.json"
system_manifest = "/run/arach-live/system.json"
init = "/system/push"

required_path = [
  "/system/push",
  "/system/corinth",
  "/system/dbus-broker-launch",
  "/system/cosmic-comp",
  "/system/cosmic-greeter",
  "/system/cosmic-session",
  "/system/cosmic-term",
  "/system/xdg-desktop-portal-cosmic",
  "/usr/libexec/arach-install",
  "/usr/bin/calamares",
  "/usr/bin/firefox",
  "/usr/share/calamares/branding/arach/arach-logo.png",
]
