---
efi:
  mountPoint: /boot/efi
  recommendedSize: 1GiB
  minimumSize: 512MiB
  label: ARACH-EFI
userSwapChoices: [none, small, suspend, file]
luksGeneration: luks2
initialPartitioningChoice: none
initialSwapChoice: none
defaultPartitionTableType: gpt
requiredPartitionTableType: gpt
defaultFileSystemType: btrfs
availableFileSystemTypes: [btrfs, ext4, xfs, f2fs]
directoryFilesystemRestrictions:
  - directory: /
    allowedFilesystemTypes: [btrfs, ext4, xfs, f2fs]
  - directory: /home
    allowedFilesystemTypes: [btrfs, ext4, xfs, f2fs]
    onlyWhenMountpoint: true
  - mountpoint: efi
    allowedFilesystemTypes: [fat32]
    onlyWhenMountpoint: true
essentialMounts: [live-*, control, ventoy]
enableLuksAutomatedPartitioning: true
preCheckEncryption: false
lvm:
  enable: true
requiredStorage: 20.0
