---
defaultGroups:
  - name: users
    must_exist: true
    system: true
  - name: wheel
    must_exist: true
    system: true
  - name: audio
    must_exist: true
    system: true
  - name: video
    must_exist: true
    system: true
  - name: input
    must_exist: true
    system: true
sudoersGroup: wheel
autologinGroup: ""
setRootPassword: true
doReusePassword: false
displayAutologin: false
doAutologin: false
passwordRequirements:
  minLength: 12
  maxLength: 256
  libpwquality:
    - minlen=12
    - maxrepeat=3
    - maxsequence=3
    - usersubstr=4
allowWeakPasswords: false
allowWeakPasswordsDefault: false
user:
  shell: /bin/bash
