[options]
HoldPkg = pacman glibc
Architecture = auto
SigLevel = Required DatabaseRequired
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[sisyphus]
SigLevel = Required DatabaseRequired
Server = https://sisyphusaeolides.github.io/Sisyphus-Repo/$arch
