---
modules-search:
  - local
  - /usr/lib/arach/calamares/modules

instances:
  - module: arachhardware
    id: preflight
    config: arach-hardware.conf
    weight: 0
  - module: arachtransaction
    id: prepare
    config: arach-prepare.conf
    weight: 1
  - module: arachtransaction
    id: commit
    config: arach-commit.conf
    weight: 8

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - arachhardware@preflight
      - arachtransaction@prepare
      - partition
      - mount
      - unpackfs
      - machineid
      - locale
      - keyboard
      - users
      - arachtransaction@commit
      - umount
  - show:
      - finished

branding: arach
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
hide-back-and-next-during-exec: true
quit-at-end: false
